"""empty message

Revision ID: 5cd5b3fe49b6
Revises: b17d6d44a63b
Create Date: 2023-05-13 22:59:24.608171

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5cd5b3fe49b6"
down_revision = "b17d6d44a63b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column("task_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("name", sa.VARCHAR(length=128), nullable=True),
        sa.Column("description", sa.VARCHAR(length=128), nullable=True),
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("task_id", name=op.f("pk_tasks")),
    )
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tasks_name"), ["name"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tasks_name"))

    op.drop_table("tasks")
    # ### end Alembic commands ###
