"""empty message

Revision ID: 4688d95e518b
Revises: 81eb743095b6
Create Date: 2023-06-26 19:37:20.857908

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4688d95e518b"
down_revision = "81eb743095b6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("custom_categories", schema=None) as batch_op:
        batch_op.add_column(sa.Column("locked", sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("custom_categories", schema=None) as batch_op:
        batch_op.drop_column("locked")

    # ### end Alembic commands ###
