"""empty message

Revision ID: 91d859bd8793
Revises: bf5fbf4077c9
Create Date: 2023-06-16 17:43:02.227799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91d859bd8793'
down_revision = 'bf5fbf4077c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classifiers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feature_count', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('feature_rows', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('training_split', sa.NUMERIC(precision=20, scale=4), nullable=True))
        batch_op.add_column(sa.Column('feature_importance_threshold', sa.NUMERIC(precision=20, scale=4), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classifiers', schema=None) as batch_op:
        batch_op.drop_column('feature_importance_threshold')
        batch_op.drop_column('training_split')
        batch_op.drop_column('feature_rows')
        batch_op.drop_column('feature_count')

    # ### end Alembic commands ###
