"""empty message

Revision ID: 3744d688bcd7
Revises: 91d859bd8793
Create Date: 2023-06-17 00:52:19.733332

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3744d688bcd7"
down_revision = "91d859bd8793"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("classifiers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("max_date", sa.DATE(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("classifiers", schema=None) as batch_op:
        batch_op.drop_column("max_date")

    # ### end Alembic commands ###
