"""empty message

Revision ID: 518a06851dd4
Revises: 5cd5b3fe49b6
Create Date: 2023-05-14 16:27:35.538472

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "518a06851dd4"
down_revision = "5cd5b3fe49b6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "custom_categories",
        sa.Column("custom_category_id", sa.INTEGER(), nullable=False),
        sa.Column("custom_category_name", sa.VARCHAR(length=100), nullable=False),
        sa.PrimaryKeyConstraint(
            "custom_category_id", name=op.f("pk_custom_categories")
        ),
    )
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("category_id", sa.INTEGER(), nullable=True))
        batch_op.add_column(
            sa.Column("custom_category_id", sa.INTEGER(), nullable=True)
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_transactions_category_id_categories"),
            "categories",
            ["category_id"],
            ["category_id"],
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_transactions_custom_category_id_custom_categories"),
            "custom_categories",
            ["custom_category_id"],
            ["custom_category_id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_transactions_custom_category_id_custom_categories"),
            type_="foreignkey",
        )
        batch_op.drop_constraint(
            batch_op.f("fk_transactions_category_id_categories"), type_="foreignkey"
        )
        batch_op.drop_column("custom_category_id")
        batch_op.drop_column("category_id")

    op.drop_table("custom_categories")
    # ### end Alembic commands ###
