"""empty message

Revision ID: 9099b08d2bb3
Revises: 462ec28837ba
Create Date: 2023-06-19 20:24:44.740229

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9099b08d2bb3"
down_revision = "462ec28837ba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("classifiers", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "training_accuracy", sa.NUMERIC(precision=20, scale=4), nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "ongoing_accuracy", sa.NUMERIC(precision=20, scale=4), nullable=True
            )
        )
        batch_op.drop_column("accuracy")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("classifiers", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "accuracy",
                sa.NUMERIC(precision=20, scale=4),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.drop_column("ongoing_accuracy")
        batch_op.drop_column("training_accuracy")

    # ### end Alembic commands ###
