"""empty message

Revision ID: 0eaa5680daaf
Revises: d8bd1b8e334c
Create Date: 2023-06-15 21:08:04.570880

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0eaa5680daaf"
down_revision = "d8bd1b8e334c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("classifiers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_active", sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("classifiers", schema=None) as batch_op:
        batch_op.drop_column("is_active")

    # ### end Alembic commands ###
