"""empty message

Revision ID: 2702574a5262
Revises: 4309ab6187f6
Create Date: 2023-05-21 22:05:22.345898

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2702574a5262"
down_revision = "4309ab6187f6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("is_operation_account", sa.BOOLEAN(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.drop_column("is_operation_account")

    # ### end Alembic commands ###
