"""empty message

Revision ID: 462ec28837ba
Revises: 8da4803c6f26
Create Date: 2023-06-19 20:12:39.391460

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "462ec28837ba"
down_revision = "8da4803c6f26"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("custom_categories", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("locked", postgresql.BIT(length=1), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("custom_categories", schema=None) as batch_op:
        batch_op.drop_column("locked")

    # ### end Alembic commands ###
