"""empty message

Revision ID: c0acf045478f
Revises: 518a06851dd4
Create Date: 2023-05-18 20:25:38.510828

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c0acf045478f"
down_revision = "518a06851dd4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.alter_column(
            "custom_category_id", existing_type=sa.INTEGER(), nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.alter_column(
            "custom_category_id", existing_type=sa.INTEGER(), nullable=True
        )

    # ### end Alembic commands ###
